freebsd_instance:
  image_family: freebsd-12-1


task:
  name: FreeBSD Build
  only_if: $CIRRUS_TAG != ''
  env:
    BASH_CMD: /usr/local/bin/bash
    CIRRUS_CLONE_DEPTH: "1"
    HOME: /tmp
    GITHUB_TOKEN: ENCRYPTED[ec1127ebd80734d2afe707a79a8fb41b1889ab7e574903649f63b8cc46aae5413699ea23a9d37fcf6e0891deced52a8a]
  install_deps_script:
    - pkg install -y curl go git bash
  install_ghr_script:
    - .cirrusci/install_ghr.sh
  install_rust_script:
    - echo "shell: $SHELL   home:$HOME"
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    - set PATH=$HOME/.cago/bin:$PATH
  build_script:
    - .cirrusci/build.sh
  deploy_script:
    - .cirrusci/deploy.sh
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
  cargo_caching_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo Cargo
