os: freebsd
language: rust

before_install:
  - set -e
  - rustup self update
  - rustup update

install:
  - cargo update

script:
  - cargo build --release

before_deploy:
  - sh .ci/before_deploy.sh

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: rmate_FreeBSD.tar.gz
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    # release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master
    - develop

notifications:
  email:
    on_success: never

