on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations

name: Full CI

env:
  OSX_SDK_VERSION: 11.1
  RUST_BACKTRACE: "1"

  # Use ",all," to run everything.
  # Or use one/more job names, comma-wrapped:
  #   ",x86_64-freebsd,"
  #   ",x86_64-freebsd,x86_64-linux-android,"
  CI_JOBS: ",x86_64-illumos,"

jobs:
  x86_64-linux:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'x86_64-unknown-linux-gnu'
      build_type: 'debug'
      run_tests: true
  i686-linux:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'i686-unknown-linux-gnu'
      build_type: 'debug'
      run_tests: true
  aarch64-linux:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'aarch64-unknown-linux-gnu'
      arm: true
      build_type: 'debug'
      run_tests: true
  armv7-linux:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'armv7-unknown-linux-gnueabihf'
      arm: true
      build_type: 'debug'
      run_tests: true
  # x86_64-macos:
  #   if: ${{ github.ref_type != 'tag' }}
  #   uses: ./.forgejo/workflows/reusable_macos.yml
  #   with:
  #     target: 'x86_64-apple-darwin'
  #     build_type: 'debug'
  #     run_tests: true
  # aarch64-macos:
  #   if: ${{ github.ref_type != 'tag' }}
  #   uses: ./.forgejo/workflows/reusable_macos.yml
  #   with:
  #     target: 'aarch64-apple-darwin'
  #     build_type: 'debug'
  #     run_tests: false
  x86_64-illumos:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-illumos,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-illumos'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  aarch64-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'aarch64-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  armv7-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'armv7-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  arm-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',arm-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'arm-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  thumbv7neon-linux-android:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',thumbv7neon-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'thumbv7neon-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-freebsd:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-freebsd,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-freebsd'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-unknown-freebsd:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-unknown-freebsd,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-unknown-freebsd'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-linux-musl:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
  aarch64-linux-musl:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'aarch64-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
  armv7-linux-musleabihf:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux-musleabihf,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'armv7-unknown-linux-musleabihf'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-linux-musl:
    runs-on: ghoolak-docker
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
# x86_64-linux-musl:
#   target: 'x86_64-unknown-linux-musl'

# aarch64-linux-musl:
#   target: 'aarch64-unknown-linux-musl'

# armv7-linux-musleabihf:
#   target: 'armv7-unknown-linux-musleabihf'

# i686-linux-musl:
#   target: 'i686-unknown-linux-musl'
