on:
  push:
    branches:
      - develop
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations

name: Quick tests on select targets

env:
  OSX_SDK_VERSION: 11.1
  RUST_BACKTRACE: "1"

  # Use ",all," to run everything.
  # Or use one/more job names, comma-wrapped:
  #   ",x86_64-freebsd,"
  #   ",x86_64-freebsd,x86_64-linux-android,"
  CI_JOBS: ",thumbv7neon-linux-android,x86_64-illumos,x86_64-macos,"

jobs:
  x86_64-linux:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'x86_64-unknown-linux-gnu'
      build_type: 'debug'
      run_tests: true
  i686-linux:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'i686-unknown-linux-gnu'
      build_type: 'debug'
      run_tests: true
  aarch64-linux:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'aarch64-unknown-linux-gnu'
      arm: true
      build_type: 'debug'
      run_tests: true
  armv7-linux:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux,')
    uses: ./.forgejo/workflows/reusable_linux.yml
    with:
      target: 'armv7-unknown-linux-gnueabihf'
      arm: true
      build_type: 'debug'
      run_tests: true
  x86_64-macos:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-macos,')
    uses: ./.forgejo/workflows/reusable_macos.yml
    with:
      target: 'x86_64-apple-darwin'
      build_type: 'debug'
      run_tests: true
  aarch64-macos:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-macos,')
    uses: ./.forgejo/workflows/reusable_macos.yml
    with:
      target: 'aarch64-apple-darwin'
      build_type: 'debug'
      run_tests: false
  x86_64-illumos:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-illumos,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-illumos'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  aarch64-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'aarch64-linux-android'
      build_type: 'debug'
      run_tests: true
      cross: true
  armv7-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'armv7-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  arm-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',arm-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'arm-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  thumbv7neon-linux-android:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',thumbv7neon-linux-android,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'thumbv7neon-linux-androideabi'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-freebsd:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-freebsd,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-freebsd'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-unknown-freebsd:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-unknown-freebsd,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-unknown-freebsd'
      build_type: 'debug'
      run_tests: true
      cross: true
  x86_64-linux-musl:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',x86_64-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'x86_64-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
  aarch64-linux-musl:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',aarch64-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'aarch64-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
  armv7-linux-musleabihf:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',armv7-linux-musleabihf,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'armv7-unknown-linux-musleabihf'
      build_type: 'debug'
      run_tests: true
      cross: true
  i686-linux-musl:
    if: contains(env.CI_JOBS, ',all,') || contains(env.CI_JOBS, ',i686-linux-musl,')
    uses: ./.forgejo/workflows/reusable_cross.yml
    with:
      target: 'i686-unknown-linux-musl'
      build_type: 'debug'
      run_tests: true
      cross: true
