name: Reusable workflow for macos

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arm:
        type: boolean
        default: false
      build_type:
        type: string
        default: 'debug'
      run_tests:
        type: boolean
        default: true

env:
  ARM: ${{ inputs.arm }}
  TARGET: ${{ inputs.target }}
  BUILD_TYPE: ${{ inputs.build_type }}
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}

jobs:
  build:
    runs-on: ghoolak-host
    name: rust-${{ matrix.rust }} (${{ inputs.build_type }})
    strategy:
      matrix:
        os: [macos-sonoma]
        rust: [stable]
    steps:
      - name: Wait for macOS VM
        run: /srv/forgejo-runner/bin/wait-macos-ci

      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive

      # - name: Check for tools (rust, pcregrep, zip)
      #   run: .forgejo/workflows/check_macos_tools.sh

      - name: Build (${{ inputs.build_type }})
        run: .forgejo/workflows/build.sh

      - name: Run test
        if: ${{ inputs.run_tests }}
        run: .forgejo/workflows/run_test.sh

      - name: Prepare release artifact
        if: ${{ github.event_name == 'workflow_dispatch' || (github.ref_type == 'tag' && matrix.rust == 'stable') }}
        run: |
          .forgejo/workflows/prepare_artifact.sh
      - name: Upload for release
        id: upload_artifact
        if: ${{ github.event_name == 'workflow_dispatch' || (github.ref_type == 'tag' && matrix.rust == 'stable') }}
        uses: https://data.forgejo.org/actions/upload-artifact@v3
        with:
          name: binary-artifact-${{ inputs.target }}
          path: |
            rmate_${{ inputs.target }}.zip
          if-no-files-found: warn
# - name: Install Rust
#   uses: actions-rs/toolchain@v1
#   with:
#     profile: minimal
#     toolchain: stable
#     target: ${{ inputs.target }}
#     override: true
