on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations

name: release

env:
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}
  OSX_SDK_VERSION: 11.1
  RUST_BACKTRACE: "1"

jobs:
  x86_64-linux:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_linux.yml
    with:
      target: 'x86_64-unknown-linux-gnu'
      build_type: 'release'
      run_tests: false
  i686-linux:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_linux.yml
    with:
      target: 'i686-unknown-linux-gnu'
      build_type: 'release'
      run_tests: false
  aarch64-linux:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_linux.yml
    with:
      target: 'aarch64-unknown-linux-gnu'
      arm: true
      build_type: 'release'
      run_tests: false
  armv7-linux:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_linux.yml
    with:
      target: 'armv7-unknown-linux-gnueabihf'
      arm: true
      build_type: 'release'
      run_tests: false
  x86_64-macos:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_macos.yml
    with:
      target: 'x86_64-apple-darwin'
      build_type: 'release'
      run_tests: false
  aarch64-macos:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_macos.yml
    with:
      target: 'aarch64-apple-darwin'
      build_type: 'release'
      run_tests: false
  x86_64-illumos:
    if: ${{ github.ref_type == 'tag' && github.ref_name != 'master' }}
    uses: ./.github/workflows/reusable_linux.yml
    with:
      target: 'x86_64-unknown-illumos'
      build_type: 'release'
      run_tests: false
      cross: true

  gh_release:
    name: Release rmate
    runs-on: ubuntu-latest
    needs: [x86_64-linux, i686-linux, aarch64-linux, armv7-linux, x86_64-macos, aarch64-macos, x86_64-illumos]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-x86_64-unknown-linux-gnu
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-i686-unknown-linux-gnu
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-aarch64-unknown-linux-gnu
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-armv7-unknown-linux-gnueabihf
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-x86_64-apple-darwin
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-aarch64-apple-darwin
      - uses: actions/download-artifact@v2
        with:
          name: binary-artifact-x86_64-unknown-illumos
      - run: ls -la /home/runner/work/rmate-rs/rmate-rs || true
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: |
            rmate_*.tar.gz
            rmate_*.zip



