name: Reusable workflow for macos

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arm:
        type: boolean
        default: false
      build_type:
        type: string
        default: 'debug'
      run_tests:
        type: boolean
        default: true

env:
  ARM: ${{ inputs.arm }}
  TARGET: ${{ inputs.target }}
  BUILD_TYPE: ${{ inputs.build_type }}
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}

jobs:
  build:
    name: macos-${{ inputs.target }} (${{ inputs.build_type }})
    runs-on: ${{ inputs.target == 'x86_64-apple-darwin' && 'macos-15-intel' || 'macos-latest' }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install pcregrep
        run: brew install pcre2

      - name: Install Rust target
        run: rustup target add "${{ inputs.target }}"

      - name: Build (${{ inputs.build_type }})
        run: .github/workflows/build.sh

      - name: Run test
        if: ${{ inputs.run_tests }}
        run: .github/workflows/run_test.sh

      - name: Prepare release artifact
        if: ${{ github.ref_type == 'tag' }}
        run: .github/workflows/prepare_artifact.sh

      - name: Upload for release
        id: upload_artifact
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/upload-artifact@v4
        with:
          name: binary-artifact-${{ inputs.target }}
          path: |
            rmate_${{ inputs.target }}.zip
          if-no-files-found: warn
